version: "3.9"

services:
  ijewelmatch:
    build: .
    container_name: ijewelmatch_app
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - SKIP_SSL_CHECK=true
    volumes:
      # OPTION A: UNC share (Docker Desktop syntax uses forward slashes)
      - //SERVER/StyleImages:/mnt/style_images:ro
      # OPTION B: mapped drive (Windows)
      # - Z:/StyleImages:/mnt/style_images:ro

      # Persist app-side data/config
      - ./data:/app/data

      # ✅ Local host folder (easy for testing)
      - ./data/images:/app/images

      # ✅ Named Docker volume (lives inside Docker, survives restarts)
      - ijewelmatch_images:/app/persist_images

volumes:
  ijewelmatch_images:
    driver: local